### PR TITLE
Add custom link name support

### PR DESCRIPTION
**Pull request by johackim**
Reference : #85

### CODE REVIEW

**Review by mathieudutour — COMMENTED** [review]
I should probably be an option because it's a breaking change otherwise

**Comment by TaylanTatli** [comment]
Any news on this?

**Comment by johackim** [comment]
Hello @TaylanTatli,

Sorry, I preferred to create a specific plugin for obsidian : https://github.com/johackim/gatsby-remark-obsidian/

Thanks for the inspiration @mathieudutour !

**Comment by TaylanTatli** [comment]
> Hello @TaylanTatli,
> 
> Sorry, I preferred to create a specific plugin for obsidian : https://github.com/johackim/gatsby-remark-obsidian/
> 
> Thanks for the inspiration @mathieudutour !

Thanks. I tried that yesterday but because of Gatsby version mismatch (2 vs 3), i couldn't managed to use it with this starter. I'm total noob on Gatsby.

**Comment by johackim** [comment]
> Thanks. I tried that yesterday but because of Gatsby version mismatch (2 vs 3), i couldn't managed to use it with this starter. I'm total noob on Gatsby.

Don't hesitate to send an issue on my repo if you have trouble to use it ;) I will be glad to help you ;)

**Pull request closed without merging**
